import crypto from 'crypto';

/**
 * One-click unsubscribe links, no login required.
 *
 * A recipient's id alone isn't secret (Firestore doc ids leak all over the
 * app), so the link needs a signature — otherwise anyone could unsubscribe
 * anyone else just by guessing an id. HMAC-signing collection+id with a
 * server-only secret means the link can only have been generated by this
 * server, and can be verified without a database round-trip.
 */

const SECRET = () => process.env.UNSUBSCRIBE_SECRET || process.env.CRON_SECRET || 'dev-only-unsubscribe-secret';

export const COLLECTIONS = { CUSTOMERS: 'users', SELLERS: 'sellers' };

export const signUnsubscribeToken = (collection, id) =>
  crypto.createHmac('sha256', SECRET()).update(`${collection}:${id}`).digest('hex').slice(0, 16);

export const verifyUnsubscribeToken = (collection, id, token) =>
  token === signUnsubscribeToken(collection, id);

export const unsubscribeHref = (siteUrl, collection, id) =>
  `${siteUrl}/api/unsubscribe?c=${collection}&id=${encodeURIComponent(id)}&t=${signUnsubscribeToken(collection, id)}`;
